### ISSUE TITLE
Attaching Zip-archive to Request

### ISSUE THREAD

**Issue by DoPinG83** [zendesk/sdk_unity_plugin#29]
Hi, guys. Is there any way to attach a zip-archive with application logs to user Request? As I see in ZDKCreateRequest-class there only strings can be attathed.

**Comment by brendan-fahy** [comment]
Hey @DoPinG83,
Adding attachments to requests in Zendesk is done in a kind of two-step process. You don't add the attachment directly to the request. You upload the attachment and get an ID, and then you add that ID to the request object. 

See [ZDKUploadProvider.UploadAttachment], which should be used for uploading attachment files. If attaching text, the String `attachment` parameter can simply be text, otherwise it should be the Base64 encoded String of the bytes of the file you want to attach. You can see the corresponding [Android](https://github.com/zendesk/sdk_unity_plugin/blob/71dd38b43ecb2324229ccdedd285394d779a7726/android-plugin/src/main/java/com/zendesk/unity/providers/UploadProvider.java#L26-L50) and [iOS](https://github.com/zendesk/sdk_unity_plugin/blob/71dd38b43ecb2324229ccdedd285394d779a7726/ios-plugin/src/ZendeskProviderUpload.m#L10-L33) implementations that handle this method. 

There's also a basic example of how to upload an attachment and attach it to a request in [ZendeskTester](https://github.com/zendesk/sdk_unity_plugin/blob/71dd38b43ecb2324229ccdedd285394d779a7726/sample/ZendeskTester.cs#L760-L791).

**Comment by DoPinG83** [comment]
Hi, @brendan-fahy. Thanks for answer. However, what I really want is to automatically attach a file to the request formed from ZDKHelpCenter. I see only ContactConfiguration-class there with AdditionalInfo-parameter. Can I use it as an attachment or it there any way to pass the attachment that I got from ZDKUploadProvider.UploadAttachment() to ZDKHelpCenter? In other words, can I get access to ZDKCreateRequest-class from ZDKHelpCenter GUI in Unity? I also see ZendeskSDK.ZDKRequestCreationConfig but no attachments-parameter there. =(

**Comment by brendan-fahy** [comment]
Hey @DoPinG83, unfortunately not. When using our UI, there is no way to automatically attach a file to a request. A user would have to attach the file themselves, or you would have to build your own UI which uses our providers, and build in the automatic uploading yourself.

**Comment by DoPinG83** [comment]
Hi again, guys. I'm attaching my test zip-archive like it's shown in your example.

byte[] attachment = File.ReadAllBytes(filePath);
string encoded = Convert.ToBase64String(attachment);
ZendeskSDK.ZDKUploadProvider.UploadAttachment(encoded, "logs.zip", "application/zip", (result, error) => {...});

After that I try to download and unzip an attachment sent from iOS and Android.
With Android-archive everything works fine.
But iOS-archive cannot be unziped unless I convert it from Base64-encoding to binary.

Do you store iOS and Android attachments in different formats? Why can't they both be just binary-files?

I attached two test archives to this commet.

[android_log_zendesk.zip](https://github.com/zendesk/sdk_unity_plugin/files/1130772/android_log_zendesk.zip)
[ios_log_zendesk.zip](https://github.com/zendesk/sdk_unity_plugin/files/1130774/ios_log_zendesk.zip)

**Comment by brendan-fahy** [comment]
Hey @DoPinG83, 

Thanks for reporting this. I had a look at our code and noticed an inconsistency between Android and iOS. Have a look at the if-statement in [Android](https://github.com/zendesk/sdk_unity_plugin/blob/master/android-plugin/src/main/java/com/zendesk/unity/providers/UploadProvider.java#L43-L47) compared to [iOS](https://github.com/zendesk/sdk_unity_plugin/blob/master/ios-plugin/src/ZendeskProviderUpload.m#L15-L26). You can see there's a significant difference in the logic being applied here. 

Officially, the Unity plugin is community-supported, which basically means I can't do a full implementation and testing cycle to try to fix this right now, but I *think* you should be able to fix it locally with the following small code change to the plugin to bring the iOS and Android implementations in line with each other.

Please try replacing this block of code in [ZendeskProviderUpload.m](https://github.com/zendesk/sdk_unity_plugin/blob/master/ios-plugin/src/ZendeskProviderUpload.m#L15-L26:
```
    if ([contentTypeHolder rangeOfString:@"text" options:NSCaseInsensitiveSearch].location != NSNotFound ||
        [contentTypeHolder rangeOfString:@"txt" options:NSCaseInsensitiveSearch].location != NSNotFound) {
        attachmentData = [GetStringParam(attachment) dataUsingEncoding:NSUTF8StringEncoding];
    }
    else if ([contentTypeHolder rangeOfString:@"image" options:NSCaseInsensitiveSearch].location != NSNotFound ||
             [contentTypeHolder rangeOfString:@"img" options:NSCaseInsensitiveSearch].location != NSNotFound) {
        attachmentData = ZDKBase64DataFromString(GetStringParam(attachment));
    }
    else {
      NSLog(@"Warning: Upload type not recognized (%@), handling attachment as string", contentTypeHolder);
      attachmentData = [GetStringParam(attachment) dataUsingEncoding:NSUTF8StringEncoding];
    }
```
with:
```
    if ([contentTypeHolder rangeOfString:@"text" options:NSCaseInsensitiveSearch].location != NSNotFound ||
        [contentTypeHolder rangeOfString:@"txt" options:NSCaseInsensitiveSearch].location != NSNotFound) {
        attachmentData = [GetStringParam(attachment) dataUsingEncoding:NSUTF8StringEncoding];
    }
    else {
        attachmentData = ZDKBase64DataFromString(GetStringParam(attachment));
    }
```
After that you'll need to rebuild the plugin and re-add it to your project. 

If you get a chance to try this, can you let us know if it works? You could even submit a pull request if you like :D otherwise we'll come back to it later. 

Regards,

Brendan

**Comment by DoPinG83** [comment]
Thanks @brendan-fahy Your suggestion works fine.

**Comment by brendan-fahy** [comment]
That's great to hear! I've created https://github.com/zendesk/sdk_unity_plugin/pull/32 with the fix, but we'll want to do some more thorough testing before merging it.

**Comment by baz8080** [comment]
Verified fix in 
https://github.com/zendesk/sdk_unity_plugin/pull/32
