### ISSUE TITLE
Android Missing auto sort feature in "My tickets" section	

### ISSUE THREAD

**Issue by mdienersberger** [zendesk/sdk_unity_plugin#60]
![android-ticketsorting](https://user-images.githubusercontent.com/34347445/33725884-ce31adba-db73-11e7-9296-436fe0ad6db5.jpg)
![ios-ticketsorting](https://user-images.githubusercontent.com/34347445/33725894-d400ca8c-db73-11e7-8b57-54e9dfa39a7a.jpg)

**Comment by baz8080** [comment]
@mdienersberger the issue here lies in the native part of the plugin. We're currently working on a 2.0 release so it's unlikely that we'll patch the 1.x branch with a fix for this. iOS and Android actually do request the same sort order from the server, but some things on the backend can cause the inconsistence that you are seeing.

**Comment by baz8080** [comment]
@mdienersberger sorry for the lack of an update until now. The native part of the work for this has been done and released on both platforms. We will be doing some exploratory work in the near term about how to bring the unity plugin up to using the native 2.x SDKs.

**Comment by baz8080** [comment]
We've [put up a branch](https://github.com/zendesk/sdk_unity_plugin/tree/android-v2) that adds support for Android and wraps the latest version of the SDK, 2.2.1. For iOS I'd recommend to continue using the master branch. The READMEs are different for each branch, and Android V2 now requires the Gradle build system in Unity.
