### ISSUE TITLE
Zendesk should not forces users to use a particular theme

### ISSUE THREAD

**Issue by rsiddub** [zendesk/sdk_unity_plugin#67]
There seems to be an issue with the zendesk unity plugin where it forces the Application  theme to be ThemeUnity.Although it is mentioned in the Readme guide, we have our own theme and do not want to use the theme required by Zendesk. When we do so, the Zendesk crashes with the error message as below

E/AndroidRuntime(15307): Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rovio.beaconsdkvalidator/com.zendesk.sdk.support.ViewArticleActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.E/AndroidRuntime(15307):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)

The crash is due to com.zendesk.sdk.support.ViewArticleActivity requiring a particular theme. We think that the Zendesk should not force its users to use the specific themes. As an alternative, the themes could be defined inside the Zendesk activity itself. 

So, for example, the com.zendesk.sdk.support.ViewArticleActivity is defined as below(We checked it by unzipping sdk-1.11.0.1.aar )

<activity
            android:name="com.zendesk.sdk.support.ViewArticleActivity"
            android:configChanges="orientation|screenSize" />

However this could be defined as
<activity
            android:name="com.zendesk.sdk.support.ViewArticleActivity"
            android:configChanges="orientation|screenSize"
	   android:theme="@style/UnityTheme" />

**Comment by baz8080** [comment]
@rsiddub sorry for the delay in getting back to you. Your message seems to have been truncated.

Our UI requires a theme that inherits from `Theme.AppCompat`.  This is because we use a few components like `Toolbar` and want them to be supported on older API levels.

You don't have to use our theme if your theme inherits from that one, and [you specify a few attributes](https://developer.zendesk.com/embeddables/docs/android/customize_the_look#use-or-extend-an-sdk-theme). Does that help?

**Comment by baz8080** [comment]
I'm going to close this as we do require Theme.Appcompat. Feel free to reopen it if you need to.
