### ISSUE TITLE
"see all X articles" barely or no visible on Helpcenter

### ISSUE THREAD

**Issue by fvangent** [zendesk/sdk_unity_plugin#75]
In the helpcenter if you have more then 5 articles it will show a "see all X articles" text and if you press it, it shows all articles. This works fine on IOS, but on android you almost can't see the the text. Even the screenshot that I made the text is compressed away. I also tried changing the colors in the "help_center_articles_style.css" but this had no effect at all.
 
Repro steps:
1) add a category in helpcenter with more then 5 articles
2) start the game and go to the helcenter in zendesk

Result:
The "see all X articles" text is barely or not visible. See red square in screenshot where it should be.

![screenshot_20180507-144136](https://user-images.githubusercontent.com/272153/39746575-ff424da2-52aa-11e8-96d7-8a017444a4b5.png)

**Comment by baz8080** [comment]
Hi @fvangent 

This is likely because the colours in your theme are not suitable for a light theme. Here's an [example of what to set](https://github.com/zendesk/sdk_demo_app_android/blob/master/app/src/main/res/values/styles.xml#L5-L7). We try to take the colours from the host app where possible.

Thanks!
