### ISSUE TITLE
App crash with latest android support libraries

### ISSUE THREAD

**Issue by daviddurston** [zendesk/sdk_unity_plugin#83]
When using newer versions of the android support libraries, the plugin crashes the app with the following error:
**java.lang.NoSuchMethodError: No static method getScreenWidthDp(Landroid/content/res/Resources;)I in class Landroid/support/v4/content/res/ConfigurationHelper;**

Seems that getScreenWidthDp has been deprecated, I believe in 26.0.0. The ConfigurationHelper class now has a getDensityDpi method. Can the plugin be updated to fix this?

Thanks so much

**Comment by KillianSmith0** [comment]
Hi @DavidDurston , we are currently working on an update for the unity plug-in with support V2. Unfortunately I can't give an exact date as to when the release will be, but will notify you when it's ready.

Killian

**Comment by daviddurston** [comment]
Thanks, looking forward to it.

**Comment by daviddurston** [comment]
Hi again, thought I'd do a one-month checkup. Just wondering if there's any chance of getting at least this one thing patched. Based on the error I presume it's a small fix (updating that one deprecated call) but I could not find that function referenced when I went looking in the SDK code, so maybe it's in some referenced code that gets imported at plugin build time or something?

Thanks, appreciate any update you can give.

**Comment by divo** [comment]
@DavidDurston unfortunately we still can't give a date for this.

**Comment by rickpt** [comment]
Hi All,

Any news when this will be available?

Google have now made API 28 support a requirement for new releases from August 2018 and app updates from November 2018

https://developer.android.com/distribute/best-practices/develop/target-sdk

So anyone using this plug-in will be unable to release/update their product. 0_0

I look forward to your response...

Thanks

Rick

**Comment by baz8080** [comment]
@rickpt @DavidDurston I can't see us directly calling `ConfigurationHelper` or `getScreenWidthDp` in the SDK code, which might mean it's more to do with the mismatch of support libraries. Is that your understanding too?

**Comment by rickpt** [comment]
@baz8080 I'm afraid I'm not sure, I'd have to undo all the work I did to force the use api 25.0.1 just to repro and provide info, but it should be a just case of building the an app with api >= 26 and trying to call ZendeskSDK.ZDKRequests.ShowRequestCreationWithConfig if you want to try and repro at your end.

**Comment by baz8080** [comment]
Hey @DavidDurston @rickpt 

We've [put up a branch](https://github.com/zendesk/sdk_unity_plugin/tree/android-v2) that adds support for Android and wraps the latest version of the SDK, 2.2.1. For iOS I'd recommend to continue using the master branch. The READMEs are different for each branch, and Android V2 now requires the Gradle build system in Unity. 

I realise it's not ideal, but I hope it can unblock you updating your app.

**Comment by rickpt** [comment]
Hi @baz8080 

Thanks that will really help we were about to start implementing a connection to RestApi instead but this should unblock our release, will let you know if this solves the issues :)

Any idea when you'll be able to support one shared plugin so we don't have to do some magic to swap between the iOS & Android versions?

Thanks

Rick

**Comment by baz8080** [comment]
HI Rick,

It's in out backlog to spend a block of time on updating iOS. We have a couple of blockers before we can get to it though.

**Comment by daviddurston** [comment]
Hi @baz8080 ,

Thanks for the update, much appreciated. Couple questions:
1) Updating from the previous release... should it be a clean install and get rid of all the plugins previously added into the Unity project, AndroidManifest changes, etc?
2) Any idea if this will work in Unity 5.6.5 if I manually create or copy over the default build.gradle file from a newer version?

**Comment by brendan-fahy** [comment]
Hey @DavidDurston, sorry for delay getting back to you. Have you had any progress on this in the meantime? I think a clean install is probably the best idea for upgrading to the v2 version. As regards Unity 5.6.5, I'm really not sure. If you can still use the gradle build system there, I think it *should* work.

**Comment by daviddurston** [comment]
Hi, just revisiting this again today now that I have cycles to spend on it.

Sorry I'm not very familiar with native Android and gradle. We do indeed use it - mostly for getting past the DEX limit though. I've built the project but when I navigate to the /tmp folder I don't see a repo folder in there. Other than that I believe I have the mainTemplate.gradle build script in working order.

What I've done is open sdk_unity_plugin-android-v2 in Android Studio and then run ./gradlew build. So I get all the Unity files and such but again, no /tmp/repo folder is created.

Right now I'm just trying to get it to work in an empty Unity 2018 project before attempting it in 5.6.5, again before trying it in our actual app project (removing the old plugin and everything it required might be a pain).

**Comment by brendan-fahy** [comment]
Hey @DavidDurston, this looks like a hole in our docs, sorry about that. The `build` task won't put anything in that tmp dir, you'll need to run `uploadArchives` for that to happen. This is explained in a bit more detail at the end of the README, https://github.com/zendesk/sdk_unity_plugin/tree/android-v2#rebuilding-the-android-plugin, but I can see how the `Integrating the Plugin` section is misleading, and doesn't really mention this step at all. I'll try to get that fixed today. 

In the meantime, can you try running `./gradlew uploadArchives` after you've run `./gradlew build`? Once that's done, you should see the artifact in the tmp dir then - or whatever directory you configure in the `uploadArchives` task in `android-plugin/build.gradle`.

**Comment by daviddurston** [comment]
Thanks @brendan-fahy , that worked and I see the /tmp/repo folder now. I'm now running up against the following error when launching the app: **java.lang.ClassNotFoundException: com.zendesk.unity.ZDK_Plugin**

The only things in this project are:
- mainTemplate.gradle file
- Zendesk C# scripts
- test scene
- test script to init & show the help center

The mainTemplate.gradle file is the default one Unity 2018 creates, plus the maven line added here:
```
buildscript {
	repositories {
		jcenter()
		maven { url 'file:///tmp/repo' }
	}
```

I'd also tried adding the maven repo line within the scope of the allprojects respositories block, and in a new top-level repositories block (figure it couldn't hurt to try). Do I need to include an AndroidManifest listing this class, or define it for the app in some way? I've reviewed all the README again, I don't think I'm missing a step. If comparing file sizes of the apk after building is a valid indicator, it doesn't seem like the repo is getting added by the gradle script.

Thanks, really appreciate the additional support here.

**Comment by danthedrummer** [comment]
I just built the AAR to have a look at the output and I can see the `ZDK_Plugin` class is there. Are you performing any obfuscation on your app?

*Edit* After looking at the docs we noticed that it doesn't mention including the dependency in Gradle. Add this line to the `dependencies` block in your `mainTemplate.gradle` and it should make the `ZDK_Plugin` available.
```groovy
dependencies {
    implementation group: "com.zendesk", name: "unityplugin", version: "2.2.1"
}
```

**Comment by daviddurston** [comment]
Alright, every post I make, I move closer to the goal haha. Here goes again...

I had to change 'implementation' to 'compile' given the version of Unity I'm on (and which version of Gradle it has) but I am now getting this error:
```
* What went wrong:
A problem occurred configuring root project 'gradleOut'.
Could not resolve all dependencies for configuration ':_debugApkCopy'.
     Could not find com.zendesk:unityplugin:2.2.1.
     Required by:
         project :
```
For the record here is my full mainTemplat.gradle. Again, this is just the standard one Unity creates, with only lines 4 and 24 added. This is building out of an empty sample project in Unity 2018.1.0f2.
```
buildscript {
	repositories {
		jcenter()
		maven { url 'file:///tmp/repo' }
	}

	dependencies {
		classpath 'com.android.tools.build:gradle:2.3.0'
	}
}

allprojects {
   repositories {
      flatDir {
        dirs 'libs'
      }
   }
}

apply plugin: 'com.android.application'

dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	compile group: "com.zendesk", name: "unityplugin", version: "2.2.1"
**DEPS**}

android {
	compileSdkVersion **APIVERSION**
	buildToolsVersion '**BUILDTOOLS**'

	defaultConfig {
		minSdkVersion	**MINSDKVERSION**
		targetSdkVersion **TARGETSDKVERSION**
		applicationId '**APPLICATIONID**'
		ndk {
			abiFilters **ABIFILTERS**
		}
		versionCode	**VERSIONCODE**
		versionName	'**VERSIONNAME**'
	}

	lintOptions {
		abortOnError false
	}

	aaptOptions {
		noCompress '.unity3d', '.ress', '.resource', '.obb'**STREAMING_ASSETS**
	}

**SIGN**
	buildTypes {
  		debug {
 			minifyEnabled **MINIFY_DEBUG**
 			useProguard **PROGUARD_DEBUG**
 			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD**
  			jniDebuggable true
  		}
  		release {
 			minifyEnabled **MINIFY_RELEASE**
 			useProguard **PROGUARD_RELEASE**
  			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'**USER_PROGUARD**
  			**SIGNCONFIG**
  		}
	}
**PACKAGING_OPTIONS**
}


**SOURCE_BUILD_SETUP**
```
I've tried moving the repository to a top-level block. I've tried moving the dependency into the buildscript block. I've tried other combinations. Cannot for the life of me get this to build. The repo folder does still exist in my tmp folder.

Side question: Because this would need to be committed to a project repo, is there a way to include it in the Unity project and point the script to it?

**Comment by danthedrummer** [comment]
Hmm I think the dependency is failing because the repository isn't available when it needs it. Try updating the `allprojects` block to look like this:
```
allprojects {
   repositories {
      flatDir {
        dirs 'libs'
      }
      maven { url 'file:///tmp/repo' }
   }
}
```

**Comment by daviddurston** [comment]
Unfortunately that was one of the other combinations/things I'd tried already. The only thing that changes is the build error, slightly:
```
* What went wrong:
A problem occurred configuring root project 'gradleOut'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find com.zendesk:support:2.2.1.
     Required by:
         project : > com.zendesk:unityplugin:2.2.1
```

I hate to ask for a "can you do it for me" instead of a "can you guide me" sort of approach but if you've built this as I'm trying to - in an empty test project - could you provide a download to that project so I can compare how it's set up? Or if the problem is solely in the gradle build script, a copy of that. I've really followed everything to a tee and don't know where to go from here.

Also, as I mentioned, I am using Unity 2018.1 to test this as the README states, but I think that may incorrect also since "implementation" doesn't seem to be supported yet and I need to revert it to "compile".

**Comment by danthedrummer** [comment]
Ok so this error looks like an internal dependency of the plugin can't be resolved so you can try updating the repositories block like so:
```
allprojects {
   repositories {
      flatDir {
        dirs 'libs'
      }
      maven { url 'file:///tmp/repo' }
      maven { url 'https://zendesk.artifactoryonline.com/zendesk/repo'}
   }
}
```
You could also try updating the gradle plugin version in the `mainTemplate.gradle`. Here's a [gist](https://gist.github.com/danthedrummer/948ff63597c510ca53763467c7c8844c) with all of the suggestions.

**Comment by rickpt** [comment]
Hi Guys,

I've been working through some of these issues here in 2017.4, after issues getting gradle to pull this stuff from the repo after uploading it I have copied your unityplugin-2.2.1.aar into our Plugins/Android folder and successfully called into it. 

(The gradle steps in the instructions only work for later versions of gradle than I can use here, so just adding the aar to my project was much easier...)

We did have an issue where there are no strings in the v2 version of the plugin so we have changed the android-plugin/res/values/strings.xml in sdk_unity_plugin gradle project to the following (mostly taken from the v1 help and added a few missing by hand)

```
<resources>
    <string name="app_name">Unity</string>
    <string name="contact_fragment_description_hint">Description</string>
    <string name="contact_fragment_email_hint">Email</string>
    <string name="contact_fragment_email_validation_error">Incorrect email address</string>
    <string name="contact_fragment_request_subject">App ticket</string>
    <string name="contact_fragment_send_button_label">Send</string>
    <string name="contact_fragment_title">Contact us</string>
    <string name="request_list_activity_title">My tickets</string>
    <string name="request_list_fragment_error_message">Failed to get tickets</string>
    <string name="request_list_fragment_no_requests">No tickets currently open</string>
    <string name="request_view_comment_entry_hint">Comment</string>
    <string name="view_request_agent_avatar_imageview_alt">Agent\'s avatar</string>
    <string name="view_request_load_comments_error">Failed to load comments</string>
    <string name="view_request_send_comment_error">Failed to send comment</string>
    <string name="articles_list_fragment_error_message">Failed to get articles</string>
    <string name="articles_list_fragment_no_articles_found">No articles found</string>
    <string name="articles_search_results_list_fragment_contact_us">Contact support</string>
    <string name="articles_search_results_list_fragment_error_message">Something went wrong</string>
    <string name="articles_search_results_list_fragment_no_articles_found">No results found</string>
    <string name="categories_list_fragment_error_message">Failed to get categories</string>
    <string name="categories_list_fragment_no_categories_found">No categories found</string>
    <string name="sections_list_fragment_error_message">Failed to get sections</string>
    <string name="sections_list_fragment_no_sections_found">No sections found</string>
    <string name="support_activity_unable_to_contact_support">Unable to contact support</string>
    <string name="support_contact_menu">Contact</string>
    <string name="support_conversations_menu">Conversations</string>
    <string name="support_list_search_hint">How can we help?</string>
    <string name="view_article_attachments_error">Failed to fetch attachments</string>
    <string name="zs_view_article_loading_title">Article Loading</string>
    <string name="view_article_seperator" translatable="false">\\u2022</string>
    <dimen name="design_bottom_sheet_modal_peek_height">0dp</dimen>
</resources>
```

This has then allowed us to reach the point where the plugin is getting initialised and we see debug logs coming back from it in App.

Right now I'm trying to reconstruct the rest of our app as we have had to disable a fair few scenes and also chunks of code in order to get the fast iteration times we needed to get this far, but I'm fairly confident that we're going to soon have the v2 plugin working in 2017 against Api 27

I hope the above will be of use to people

So... @baz8080 @brendan-fahy where do we get all of the strings from and how do we ensure that it is going to use the localised versions?

Cheers

Rick

**Comment by daviddurston** [comment]
Hey @danthedrummer , I've tried a few different things and getting different errors from each one. Included in what I've tried is upping Unity 2018.1's internal gradle library from 4.0.1 to 5.0.0.

Using your gist and 4.0.1:
> Failed to apply plugin [id 'com.android.application']
   \- Minimum supported Gradle version is 4.6. Current version is 4.0.1. If using the gradle wrapper, try editing the distributionUrl in /Users/david/Projects/_testProject/Temp/gradleOut/gradle/wrapper/gradle-wrapper.properties to gradle-4.6-all.zip

Using your gist and 5.0.0:
> Cannot invoke method packagingOptions() on null object

@rickpt , I'd previously, and I guess too briefly, tried what you did. Glad you're making progress in that way.

**Comment by rickpt** [comment]
@baz8080 @brendan-fahy Hey, we're still having trouble here,

The call "ZendeskSDK.ZDKConfig.Initialize" is failing with "Something went wrong during Zendesk setup: java.lang.NoClassDefFoundError: Failed resolution of: Lzendesk/core/Zendesk;"

We've opened up the _unity-plugin-2.2.1.aar_ file (the old rename to zip and extract method) and cannot the find the class definitions within.

We've also gone back to the start and tried using your method in 2018.3 (and .2) and we had no success here because the unity gradle build is looking for _unity-plugin-2.2.1.jar_ and .pom and we have an .aar not a .jar.

If can provide either an functioning example unity project that will allow us to build, test and then replicate into our projects we'd really appreciate it as would all the others in this thread.

Thanks in advance

Rick

**Comment by baz8080** [comment]
Hey All, I just tried a sample app this morning and it's working for me using version 2.2.1 on Unity 2018.2. I was using the android-v2 branch. You'll need to add your own app details in ZendeskExample.cs
[New Unity Project.zip](https://github.com/zendesk/sdk_unity_plugin/files/2690160/New.Unity.Project.zip)

**Comment by FixitFrank** [comment]
We are also having problems to get this to work. After uploadArchives I just copy the unityplugin-2.2.1.aar from the /tmp/res to the /Assets/Plugins/Android and we also get the same NoClassError as reported above.


01-08 19:12:26.641 26959 27001 I Unity   : ZendeskSDK.ZDKBaseComponent:Log(String) (at /projects/tmh/Assets/Zendesk/Scripts/ZDKBaseComponent.cs:13)
01-08 19:12:26.641 26959 27001 I Unity   : ZendeskSDK.ZDKBaseComponent:DoImpl(Boolean, Boolean, String, Object[]) (at /projects/tmh/Assets/Zendesk/Scripts/ZDKBaseComponent.cs:129)
01-08 19:12:26.641 26959 27001 I Unity   : ZendeskSDK.ZDKBaseComponent:Do(String, Object[]) (at /projects/tmh/Assets/Zendesk/Scripts/ZDKBaseComponent.cs:106)
01-08 19:12:26.641 26959 27001 I Unity   : ZendeskSDK.ZDKConfig:Initialize(GameObject, String, String, String) (at /projects/tmh/Assets/Zendesk/Scripts/ZDKConfig.cs:64)
01-08 19:12:26.641 26959 27001 I Unity   : <Start>c__Iterator0:MoveNext() (at /projects/tmh/Assets/Scripts/Helpers/ZendeskHelper.cs:45)
01-08 19:12:26.641 26959 27001 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
01-08 19:12:26.641 26959 27001 I Unity   :  
01-08 19:12:26.641 26959 27001 I Unity   : (Filename: /projects/tmh/Assets/Zendesk/Scripts/ZDKBaseCo
01-08 19:12:26.665 26959 27001 D Gu3Shared: backup.get from prefs:tmh:development:GDPR.optOut = 0
01-08 19:12:26.665 26959 27001 E Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lzendesk/core/Zendesk;
01-08 19:12:26.665 26959 27001 E Unity   : java.lang.NoClassDefFoundError: Failed resolution of: Lzendesk/core/Zendesk;
01-08 19:12:26.665 26959 27001 E Unity   : 	at com.zendesk.unity.ZDK_Plugin.initialize(ZDK_Plugin.java:79)
01-08 19:12:26.665 26959 27001 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
01-08 19:12:26.665 26959 27001 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
01-08 19:12:26.665 26959 27001 E Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source)
01-08 19:12:26.665 26959 27001 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:98)
01-08 19:12:26.665 26959 27001 E Unity   : 	at android.os.Looper.loop(Looper.java:154)
01-08 19:12:26.665 26959 27001 E Unity   : 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source)
01-08 19:12:26.665 26959 27001 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "zendesk.core.Zendesk" on path: DexPathList[[zip file "/data/app/se.foglo.tmh-1/base.apk"],nativeLibraryDirectories=[/data/app/se.foglo.tmh-1/lib/arm, /data/app/se.foglo.tmh-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
01-08 19:12:26.665 26959 27001 E Unity   : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-08 19:12:26.665 26959 27001 E Unity   : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)


It apperently can't find import zendesk.core.Zendesk in ZDK_plugin.java. Any idea what goes wrong here? We also use V2.2.1. Note that it doesn't really matter if I copy the aar to the plugin folder, or let it import through the gradle config. It just generates the same error. Btw, the 1.11.2.1 just works fine. Some help would be welcome!

Thanks!

**Comment by MAbdullahMalik** [comment]
@FixitFrank  Are you able to solve it?

**Comment by MAbdullahMalik** [comment]
Everything working as expected. Thank you @baz8080 for your project

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-
